/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.MainControlador;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author inigu
 */
public class MainWindow extends javax.swing.JFrame {
    MainControlador controlador = new MainControlador(this);
    public MainWindow() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.pintarimagen();
        btPacientes.addActionListener(controlador);
        btnPsicologo.addActionListener(controlador);
        btConsultas.addActionListener(controlador);
        btSalir.addActionListener(controlador);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btPacientes = new javax.swing.JButton();
        btnPsicologo = new javax.swing.JButton();
        btConsultas = new javax.swing.JButton();
        btSalir = new javax.swing.JButton();
        equipo = new javax.swing.JLabel();
        circulo = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btPacientes.setText("Paciente");
        jPanel1.add(btPacientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 80, 89, 32));

        btnPsicologo.setText("Psicologo");
        jPanel1.add(btnPsicologo, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 80, 110, 32));

        btConsultas.setText("Consultas");
        jPanel1.add(btConsultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 80, 110, 32));

        btSalir.setText("Salir");
        jPanel1.add(btSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 6, 89, 32));
        jPanel1.add(equipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 260, 210));
        jPanel1.add(circulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 260, 210));
        jPanel1.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 350));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pintarimagen(){
        ImageIcon fndo = new ImageIcon("src\\images\\Colors.jpg");
        ImageIcon iconof = new ImageIcon(fndo.getImage().getScaledInstance(this.fondo.getWidth(), this.fondo.getHeight(), Image.SCALE_DEFAULT));
        this.fondo.setIcon(iconof);
        this.repaint();
        ImageIcon cir = new ImageIcon("src\\images\\circle.png");
        ImageIcon iconocir = new ImageIcon(cir.getImage().getScaledInstance(this.circulo.getWidth(), this.circulo.getHeight(), Image.SCALE_DEFAULT));
        this.circulo.setIcon(iconocir);
        this.repaint();
        ImageIcon eq = new ImageIcon("src\\images\\SCP Logo.png");
        ImageIcon iconoeq = new ImageIcon(eq.getImage().getScaledInstance(this.equipo.getWidth(), this.equipo.getHeight(), Image.SCALE_DEFAULT));
        this.equipo.setIcon(iconoeq);
        this.repaint();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btConsultas;
    public javax.swing.JButton btPacientes;
    public javax.swing.JButton btSalir;
    public javax.swing.JButton btnPsicologo;
    private javax.swing.JLabel circulo;
    private javax.swing.JLabel equipo;
    private javax.swing.JLabel fondo;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
